### ISSUE TITLE
Typos in the README?

### ISSUE THREAD

**Issue by onyxbits** [xiaxiaocao/apk-parser#23]
> From version 2.0, apk-parser requires java8. The last version support java6 is 1.7.4.

According to the commit log, this should be java7 and 1.4.7?

**Comment by xiaxiaocao** [comment]
Yes.. It should be java7.  however version 1.7.4 for java6 did exist.
Recently use gralde to publish lib to maven central repo, which will not auto create git commit for one new version

**Comment by xiaxiaocao** [comment]
fixed
