### ISSUE TITLE
jdk6 branch ：类ApkParser的方法parseCertificate一点疑问

### ISSUE THREAD

**Issue by lumeng689** [xiaxiaocao/apk-parser#28]
您好，我在使用中发现一个疑问，麻烦帮忙解答一下：

ApkParser类的方法parseCertificate中，看代码是通过循环压缩包内文件来查找以.RSA或.DSA文件，如果apk包内没有找到这个文件的话，entry变量会保留最后一次的那个文件，是否在while语句块里的最后一句处理一下，设置 entry = null?
<pre>
        while (enu.hasMoreElements()) {
            entry = enu.nextElement();
            if (entry.isDirectory()) {
                continue;
            }
            if (entry.getName().toUpperCase().endsWith(".RSA")
                    || entry.getName().toUpperCase().endsWith(".DSA")) {
                break;
            }
            // 是否应该这么处理一下？
            entry = null;
        }
</pre>

**Comment by xiaxiaocao** [comment]
是的，你是对的。我会修改一下

**Comment by xiaxiaocao** [comment]
fixed in https://github.com/xiaxiaocao/apk-parser/commit/d7a86d41e5547d761475af09bc711b4baef807d9
